//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApmMedical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card_patiet
    {
        public int id_card { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public Nullable<int> id_patient { get; set; }
        public Nullable<int> id_disease { get; set; }
        public string temperature { get; set; }
        public string pressure { get; set; }
        public string pulse_rate { get; set; }
        public string weight { get; set; }
    
        public virtual disease disease { get; set; }
        public virtual Info_doctors Info_doctors { get; set; }
        public virtual Info_patient Info_patient { get; set; }
    }
}
