//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApmMedical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info_patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Info_patient()
        {
            this.Card_patiet = new HashSet<Card_patiet>();
        }
    
        public int id_patient { get; set; }
        public string fitstname_patient { get; set; }
        public string surname_patient { get; set; }
        public string lastname_patient { get; set; }
        public System.DateTime year_patient { get; set; }
        public Nullable<int> id_sex { get; set; }
        public Nullable<int> id_blood { get; set; }
    
        public virtual Bloods Bloods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_patiet> Card_patiet { get; set; }
        public virtual Sex Sex { get; set; }
    }
}
