//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApmMedical.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApmMedicEntities : DbContext
    {
        public ApmMedicEntities()
            : base("name=ApmMedicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bloods> Bloods { get; set; }
        public virtual DbSet<Card_patiet> Card_patiet { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<disease> disease { get; set; }
        public virtual DbSet<Info_doctors> Info_doctors { get; set; }
        public virtual DbSet<Info_patient> Info_patient { get; set; }
        public virtual DbSet<Info_reception> Info_reception { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Temperature_sheet> Temperature_sheet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
