//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApmMedical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperature_sheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temperature_sheet()
        {
            this.Card_patiet = new HashSet<Card_patiet>();
        }
    
        public int id_temp { get; set; }
        public Nullable<int> Id_patient { get; set; }
        public Nullable<int> id_doctor { get; set; }
        public string temperature { get; set; }
        public string pressure { get; set; }
        public string pulse_rate { get; set; }
        public string weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Card_patiet> Card_patiet { get; set; }
    }
}
