//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApmMedical.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temperature_sheet
    {
        public int id_temp { get; set; }
        public int Id_patient { get; set; }
        public int id_doctor { get; set; }
        public string temperature { get; set; }
        public string pressure { get; set; }
        public string pulse_rate { get; set; }
        public string weight { get; set; }
    }
}
